name: se7ety
description: "A new Flutter project."
publish_to: "none"
version: 0.1.0

environment:
  sdk: ">=3.2.0 <4.0.0"

dependencies:
  cached_network_image: ^3.4.1
  cloud_firestore: ^5.6.8
  firebase_auth: ^5.5.4
  firebase_core: ^3.13.1
  firebase_messaging: ^15.2.6
  flutter:
    sdk: flutter
  flutter_bloc: ^9.1.1
  flutter_image_compress: ^2.4.0
  flutter_launcher_icons: ^0.14.4
  flutter_local_notifications: ^19.3.1
  flutter_localizations:
    sdk: flutter
  flutter_svg: ^2.1.0
  gap: ^3.0.1
  google_nav_bar: ^5.0.7
  http: ^1.4.0
  image_picker: ^1.1.2
  intl: ^0.19.0
  lottie: ^3.1.0
  path_provider: ^2.1.5
  permission_handler: ^11.3.0
  shared_preferences: ^2.1.1
  smooth_page_indicator: ^1.2.1
  url_launcher: ^6.1.11

dev_dependencies:
  flutter_lints: ^3.0.1
  flutter_test:
    sdk: flutter

flutter_launcher_icons:
  image_path: "assets/images/icon.png"
  android: true
  ios: true

flutter:
  uses-material-design: true

  assets:
    - assets/images/

  fonts:
    - family: Cairo
      fonts:
        - asset: assets/fonts/Cairo-Regular.ttf
          weight: 400
        - asset: assets/fonts/Cairo-Medium.ttf
          weight: 500
        - asset: assets/fonts/Cairo-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Cairo-Bold.ttf
          weight: 700
